### PR TITLE
Fix scene values type 'list' (Partially fix #266)

### LINKED ISSUE #266: Bug: addSceneValue not working as expected
There is no support in addSceneValue for 'list' type and the 'decimal' type doesn't works

(BUG ---> 'SceneGetValueAsString' should be 'SceneGetValueListSelection')
https://github.com/OpenZWave/node-openzwave-shared/blob/master/src/utils.cc#L200

https://github.com/OpenZWave/node-openzwave-shared/blob/master/src/utils.cc#L200

 but OpenZwaveManager has them:

https://github.com/OpenZWave/open-zwave/blob/master/dotnet/src/ZWManager.h#L2043

https://github.com/OpenZWave/open-zwave/blob/master/dotnet/src/ZWManager.h#L2083

### PR DESCRIPTION
**Pull request by robertsLando**
This is a partially fix of #266.

Please @ekarak check this commit. I have fixed list type values on scenes but there are still errors with 'decimal' types. The value is correctly stored in scene value (also in zwscene.xml) but when the scene is activate the value is not correctly parsed and it is set to default: 

The value in `zwscene.xml`
```xml
<Value homeId="0xe84dc80d" nodeId="3" genre="user" commandClassId="67" instance="1" index="1" type="decimal">30.500000</Value>
```

When I call activateScene: 
`zwave node 3: changed: 67:Heating:20.0 -> 5.0`

It is set to 5 that is the min value.

This is the returned object value from `getSceneValues`

```javascript
{ value_id: '3-67-1-1',
    node_id: 3,
    class_id: 67,
    type: 'decimal',
    genre: 'user',
    instance: 1,
    index: 1,
    label: 'Heating',
    units: 'C',
    help: '',
    read_only: false,
    write_only: false,
    min: 0,
    max: 0,
    is_polled: false,
    value: '30.500000' }
```

### CODE REVIEW

File: src/openzwave-scenes.cc [hunk 1]
```diff
@@ -137,7 +137,7 @@ namespace OZW {
 				}
 				case OpenZWave::ValueID::ValueType_Decimal: {
 					//float val; OpenZWave::Manager::Get()->GetValueAsFloat(*vit, &val);
-					float val = Nan::To<Number>(info[valoffset]).ToLocalChecked()->NumberValue();
+					float val = Nan::To<Number>(info[valoffset]).ToLocalChecked()->Value();
```
Comment (robertsLando) [inline src/openzwave-scenes.cc]: This is a try but is working like `->NumberValue()`

**Comment by ekarak** [comment]
thanks!
